server:
  port: 81
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:root@eureka:7001/eureka,http://admin:root@eureka2:7002/eureka,http://admin:root@eureka3:7003/eureka
feign:
  hystrix:
    enabled: true
