server:
  port: 8082
mybatis:
  mapper-locations: # 所有的mapper映射文件
    - classpath:mapping/*.xml
spring:
  application:
    name: myspringcloud-provider-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
#    driver-class-name: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
      #    因为降低了springboot版本( <version>2.0.7.RELEASE</version>)，所以生产者产品服务数据库驱动类需要进行修改
    driver-class-name: com.mysql.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/springcloud2?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root
    password: root
logging:
  level:
    com.en.mapper: debug
eureka:
  client: #客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:root@eureka:7001/eureka,http://admin:root@eureka2:7002/eureka,http://admin:root@eureka3:7003/eureka
  instance:
    instance-id: microcloud-provider-product2
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔（默认是90秒）
info:
  app.name: myspringcloud-provider-product2
  company.name: en
  build.artifactId: myspringcloud-provider-product2
  build.modelVersion: 4.0.0
