server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:root@eureka:7001/eureka,http://admin:root@eureka2:7002/eureka,http://admin:root@eureka3:7003/eureka
    register-with-eureka: false

spring:
  application:
    name:  myspringcloud-zuul-gateway
  security:
    user:
      name: admin
      password: root

zuul:
  routes:
    users:
      path: /users-proxy/**
      serviceId: myspringcloud-provider-users-hystrix
    product:
      path: /product-proxy/**
      serviceId: myspringcloud-provider-product
  ignored-services:
    "*"
  prefix: /myspringcloud-api


