server:
  port: 9101
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:root@eureka:7001/eureka,http://admin:root@eureka2:7002/eureka,http://admin:root@eureka3:7003/eureka

turbine:
  app-config: MYSPRINGCLOUD-PROVIDER-PRODUCT-HYSTRIX,MYSPRINGCLOUD-PROVIDER-USERS-HYSTRIX
  cluster-name-expression: new String("default")
